---
- name: Retrieve current cluster name
  rabbitmq_global_parameter:
    name: cluster_name
    value: "{{ rabbitmq_cluster_name | to_json }}"
    state: present
  when: rabbitmq_cluster_name | default("", True) != ""
