---
- name: set erlang cookie
  template:
    src: erlang.cookie.j2
    dest: "{{ rabbitmq_erlang_cookie_file }}"
    owner: rabbitmq
    group: rabbitmq
    mode: 0400
  notify: "{{ rabbitmq_restart_handler }}"

- name: ensure old config file does not exist
  file:
    path: /etc/rabbitmq/rabbitmq.config
    state: absent
  notify: "{{ rabbitmq_restart_handler }}"

- name: configure rabbitmq
  template:
    src: rabbitmq.conf.j2
    dest: /etc/rabbitmq/rabbitmq.conf
  notify: "{{ rabbitmq_restart_handler }}"
  when: rabbitmq_config is defined

- name: configure rabbitmq environment
  template:
    src: rabbitmq-env.conf.j2
    dest: /etc/rabbitmq/rabbitmq-env.conf
  notify: "{{ rabbitmq_restart_handler }}"
  when: rabbitmq_env is defined

- name: Retrieve current cluster name
  shell: 'rabbitmqctl cluster_status | grep -oP "Cluster name: \K(.*)"'
  changed_when: False  # read only
  check_mode: False
  register: cluster_name
  when: rabbitmq_cluster_name | default("", True) != ""

- name: Set cluster name
  command: "rabbitmqctl set_cluster_name {{ rabbitmq_cluster_name }}"
  when: >
    rabbitmq_cluster_name | default("", True) != ""
    and cluster_name.stdout != rabbitmq_cluster_name
