---
- name: include rabbitmq installation tasks
  include: install-{{ ansible_os_family }}.yml

- include: plugins.yml

- include: configure.yml

- name: flush handlers
  meta: flush_handlers

- name: ensure rabbitmq-server is started
  service:
    name: rabbitmq-server
    enabled: true
    state: started

- include: vhosts.yml

- include: users.yml

- include: policies.yml
